Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,6 +1,3 @@
-# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
-
 name: Deploy on Leffe
 
 on:
@@ -22,13 +19,17 @@ jobs:
 
     - name: Copy files via SSH using sshpass
       env:
-          environment: SSH_PASSWORD
-          SSHPASS: ${{ secrets.SSH_PASSWORD }}
+        SSHPASS: ${{ secrets.SSH_PASSWORD }}
       run: |
         sshpass -e ssh -o StrictHostKeyChecking=no -p 8022 jari@leffe.science.uva.nl << 'EOF'
           echo 'SSH connection successful'
-          # Add your commands here
-          cd /web/jari/
+          cd /web/jari/BabylonSignLab
           /web/jari/executeUpdate.sh
-          # Additional commands can be added here
+          EXIT_CODE=$?
+          if [ $EXIT_CODE -ne 0 ]; then
+            echo "Deployment failed."
+            exit $EXIT_CODE
+          else
+            echo "Deployment succeeded."
+          fi
         EOF
